blank_issues_enabled: false

contact_links:
  - name: 💬 M2Dev Discussion Thread
    url: https://metin2.dev/board/topic/2747-worldeditor-remix/
    about: General questions, help, and community discussion
